import React, { Component } from 'react';
import './App.css';
import AppHeader from './AppHeader.js';
import Introduce from './Introduce.js';
import About from './About.js';
import Experience from './Experience.js';
import Education from './Education.js';
import SchoolIcon1 from './school_icon1.png';
import SchoolIcon2 from './school_icon2.png';
import Portfolio from './Portfolio.js';
import PortfolioPic from './portfolio_pic.jpg';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="Home-content-container">
          <AppHeader className="AppHeader" />
          <Introduce className="Introduce" />
          <About className="About" id="about" />
          <Experience className="Experience" id="work" experiences={experiences} />
          <Education className="Education" educations={educations} />
          <Portfolio className="Portfolio" portfolios={portfolios}/>
        </div>
      </div>
    );
  }
}

const experiences = [
  {
    id:"0", title: "JavaScript Engineer", company: "Gears of Leo",
    startDate: "2016.10", endDate: "Now",
    summary: "Mainly responsible for frontend development with Backbone, including service development using NodeJS. Maintain and upgrade existing systems, migrate old frontend framework to React, both for mobile and desktop. Agile development, Jira, Jenkins, CI workflow. ES6."
  },
  {
    id:"1", title: "Algorithm Developer", company: "VionLabs",
    startDate: "2015.01", endDate: "2016.09",
    summary: "Implement prototype of the content-based recommender system for the movie website. Analyze movie data and visualize by Kibana. Implement React components for the Movie Analysis website."
  },
  {
    id:"2", title: "IMS Software Developer Intern", company: "Ericsson",
    startDate: "2014.06", endDate: "2014.08",
    summary: "Software Developer Assistant - Product Development - R&D I was in the SBG(Session Border Gateway) department during my summer internship in Ericsson R&D Shanghai Branch. My task was to improve the performance of the code upgrade. We wrote Erlang program to distribute different tasks to different containers which was generated by Docker. We tried to retrieve files which are related to the ClearCase from SSIT and migrated them to Docker."
  }
];

const educations = [
  {
    id:"0", schoolIcon: SchoolIcon1, schoolName:"DongFeng High School",
    startDate:"2006", endDate:"2009", major:"Engineering"
  },
  {
    id:"1", schoolIcon: SchoolIcon2, schoolName:"Hubei University",
    startDate:"2009", endDate:"2013", major:"B.Eng. in Computer Science"
  }
];

const portfolios = [
  {
    id:"0", pic:PortfolioPic, title:"LeoVegas", desc:"LeoVegas desktop and mobile web development"
  },
  {
    id:"1", pic:PortfolioPic, title:"CV", desc:"LeoVegas desktop and mobile web development"
  },
  {
    id:"2", pic:PortfolioPic, title:"New Forum", desc:"LeoVegas desktop and mobile web development"
  },
  {
    id:"3", pic:PortfolioPic, title:"Movie Analysis", desc:"LeoVegas desktop and mobile web development"
  },
  {
    id:"4", pic:PortfolioPic, title:"Blog", desc:"LeoVegas desktop and mobile web development"
  },
];

export default App;
