import React, { Component } from 'react';
import './App.css';
import AppHeader from './AppHeader.js';
import Introduce from './Introduce.js';
import About from './About.js';
import Experience from './Experience.js';

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="Home-content-container">
          <AppHeader className="AppHeader" />
          <Introduce className="Introduce" />
          <About className="About" id="about" />
          <Experience className="Experience" id="work" experiences={experiences} />
        </div>
      </div>
    );
  }
}

const experiences = [
  {
    id:"0", title: "JavaScript Engineer", company: "Gears of Leo", 
    startDate: "2016.10", endDate: "Now",
    summary: "Mainly responsible for frontend development with Backbone, including service development using NodeJS. Maintain and upgrade existing systems, migrate old frontend framework to React, both for mobile and desktop. Agile development, Jira, Jenkins, CI workflow. ES6."
  },
  {
    id:"1", title: "Algorithm Developer", company: "VionLabs", 
    startDate: "2015.01", endDate: "2016.09",
    summary: "Implement prototype of the content-based recommender system for the movie website. Analyze movie data and visualize by Kibana. Implement React components for the Movie Analysis website."
  },
  {
    id:"2", title: "IMS Software Developer Intern", company: "Ericsson", 
    startDate: "2014.06", endDate: "2014.08", 
    summary: "Software Developer Assistant - Product Development - R&D I was in the SBG(Session Border Gateway) department during my summer internship in Ericsson R&D Shanghai Branch. My task was to improve the performance of the code upgrade. We wrote Erlang program to distribute different tasks to different containers which was generated by Docker. We tried to retrieve files which are related to the ClearCase from SSIT and migrated them to Docker."
  }
];

export default App;
